version: "3"

services:
  stonal-api:
    build: .
    image: stonal-api
    ports:
      - "8000:8000"
    depends_on:
      - stonal-db
    environment:
      db_name: mydatabase
      db_user_name: postgres
      db_password: password
      db_host: stonal-db
      db_port: "5432"
    links:
      - stonal-db

  stonal-db:
    container_name: stonal-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
