"""Add unique constraint

Revision ID: b16bd908716e
Revises: 5ae25ca25dff
Create Date: 2025-11-07 14:22:44.084506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16bd908716e'
down_revision: Union[str, Sequence[str], None] = '5ae25ca25dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_employee_email', 'Employees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_employee_email', 'Employees', type_='unique')
    # ### end Alembic commands ###
